---
- name: Create AWS S3 Bucket
  hosts: localhost
  gather_facts: false
  vars:
    bucket_name: "ansible-s3-test-bucket"
    encryption_type: "AES256"
    s3_acl: "public-read"
  tasks:
    - name: Create bucket
      amazon.aws.s3_bucket:
        name: "{{ bucket_name }}"
        state: present
        encryption: "{{ encryption_type }}"
      register: created_bucket

    - name: Block S3 public access
      ansible.builtin.command: >
        aws s3api put-public-access-block
          --bucket {{ bucket_name }}
          --public-access-block-configuration
            "BlockPublicAcls=false,
            IgnorePublicAcls=false,
            BlockPublicPolicy=true,
            RestrictPublicBuckets=true"        
      when: block_public_access
